export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const HASH_SERVICE = Symbol('HASH_SERVICE');
export const TOKEN_SERVICE = Symbol('TOKEN_SERVICE');
export const PASSWORD_RECOVERY_REPOSITORY = Symbol('PASSWORD_RECOVERY_REPOSITORY');
